-- Create a specific application user with limited privileges
-- Replace 'password' with a strong password generated by a secrets manager

CREATE USER IF NOT EXISTS 'booking_app' @'%' IDENTIFIED BY 'StrongAppPassword123!';

-- Grant specific privileges on the application database only
GRANT
SELECT,
INSERT
,
UPDATE,
DELETE ON booking_system.* TO 'booking_app' @'%';

-- Revoke dangerous privileges
REVOKE
DROP,
ALTER,
TRUNCATE ON booking_system.*
FROM 'booking_app' @'%';

-- Flush privileges to apply
FLUSH PRIVILEGES;